### ISSUE TITLE
Args out of range: [], 0

### ISSUE THREAD

**Issue by ikzk** [cute-jumper/gscholar-bibtex#11]
Whenever I use google scholar, it gives me the `args out of range: [], 0` error on querying the bibtex. Other  options such as DBLP work fine.

I also tried to reinitialize my `.emacs.d` directory and remove `.w3m` directory, but the problem persists.

**Comment by cute-jumper** [comment]
Is this related to https://github.com/cute-jumper/gscholar-bibtex/issues/10? And also, please provide more details so that I could reproduce the problem.

**Comment by ikzk** [comment]
@cute-jumper Thanks for your comment. I have read that issue before I opened this. I think this is probably a different problem since my error is slightly different from that issue (the number in my error message is 0) and I can get the links to the `*.bib`s from

```
(let* ((url-request-method "GET")
    (url-request-extra-headers
     `(("User-Agent" . "Mozilla/5.0")
       ("Cookie" . "GSP=ID=87969bbbc5530bab:CF=4"))))
  (url-retrieve "https://scholar.google.com/scholar?q=test"
        (lambda (status) (switch-to-buffer (current-buffer)))))
```

I simply installed the package and run `gscholar-bibtex` and select `google scholar` and then use any keys such as `a A` on any entry, it will show this error.

**Comment by cute-jumper** [comment]
IIUC, you can see the search results but can't type `tab` on any result? And can you give me the backtrace using `M-x toggle-debug-on-error`?

**Comment by ikzk** [comment]
@cute-jumper Sorry for replying late. Yes, that's exactly what happened.
........... However, after I toggle the `toggle-debug-on-error`, the problem that has lasted for more than 2 weeks disappeared! I cannot explain what happened (It's too weird to think it as the debug mode magically fix the problem. Probably it is fixed by an update of my arch linux system...) ... Maybe I'll close this issue and tell you what happened if this problem appears again...

Thanks for your work on this really useful tool!
