### ISSUE TITLE
IEEE search can't find IEEE papers that Google Scholar can find

### ISSUE THREAD

**Issue by notuntoward** [cute-jumper/gscholar-bibtex#19]
gscholar-bibtex gets many hits if I search Google Scholar for this IEEE paper:

    Bandwidth Allocation Algorithm of IEEE802.16j Relay Network Based on Utility Optimalizing

However, if I use gscholar-bibtex to search IEEE for it, I get no hits.  But it is actually on IEEE here:

    http://ieeexplore.ieee.org/document/7917138/

**Comment by cute-jumper** [comment]
Thanks for reporting! It seems IEEE has change its search interface. I'll have to investigate a little bit and further to fix the problem.

**Comment by cute-jumper** [comment]
Done. Tested on my machine and it seemed to work. Can you confirm that whether the new version works?

**Comment by notuntoward** [comment]
Thanks.  I just tested the version that just came over melpa and noticed that the Gscholar search result was improved, in that it returned only this exact paper.  But, for me, at least, the IEEE result was not better.  Now, when I search for this paper, I get no hits but do get this message in my minibuffer:

json-read: End of file while parsing JSON

**Comment by cute-jumper** [comment]
Hmm. Weird. What is the keyword you use to search this paper? I used "bandwidth allocation" and this paper showed as the first entry.

**Comment by notuntoward** [comment]
I was using the whole title, but if I use "bandwidth allocation" I get the same result.  If I look in the *Messages* buffer, I see:

Contacting host: ieeexplore.ieee.org:80
json-read: End of file while parsing JSON

I don't quite understand the function gscholar-bibtex-ieee-search-results, but inside it, I see the string "http://ieeexplore.ieee.org/rest/search"

If I paste that into my browser, I get the message: "Request method 'GET' not supported"

Not sure if that's expected...

**Comment by cute-jumper** [comment]
I hope it could be fixed by the latest commit. I can now use the whole title to search this paper.

**Comment by notuntoward** [comment]
Hi, did you commit another version since my last message?  If so, should I expected it on elpa soon?  If not, what I have when I wrote my last message doesn't work, either with a full title or with a few words of it.

**Comment by cute-jumper** [comment]
Yes. I've pushed a new commit. The new version should appear on MELPA in a few hours.

**Comment by notuntoward** [comment]
Thanks!  The latest commit works for me.  

One thing missing is that it doesn't download the abstract.  Would it be possible for you to add that option?

**Comment by cute-jumper** [comment]
Currently this package only aims to quickly fetch the BibTeX entries, and is not meant to replace the browser. Although it is possible to get the abstract (or other related information) from some sources, I probably won't implement such a feature (by myself). But I'm not against it. If someone submits a PR, I would happily accept it.

**Comment by notuntoward** [comment]
OK, thanks.
