### ISSUE TITLE
怎样配合 socks proxy 使用呢？

### ISSUE THREAD

**Issue by et2010** [cute-jumper/gscholar-bibtex#24]
有没有办法使用 socks proxy 呢？因为国内网络的原因，无法使用您的这款插件。我现在的 workaround 是使用 proxy wrapper，但是这样每次启动 emacs 都全局使用 proxy，这是我希望避免的。有没有什么好的解决办法呢？谢谢！

**Comment by cute-jumper** [comment]
才看见，GitHub 首页现在不显示 issue 了。我也不清楚哈。Google 了一下发现你已经解决了：https://gist.github.com/et2010/5d6edeeb284e33343d0a

**Comment by et2010** [comment]
不知道为什么，那样设置并没有用

**Comment by cute-jumper** [comment]
尝试过 https://www.gnu.org/software/emacs/manual/html_mono/url.html#index-url_002dproxy_002dservices-116 么？
