### ISSUE TITLE
gscholar-bibtex--write-bibtex-to-file-impl: Args out of range: [], 0

### ISSUE THREAD

**Issue by GMTSE** [cute-jumper/gscholar-bibtex#34]
Hi
Searching GScholar works but I get the following errors when trying to access [TAB]/copy[c] the bibtex entry:
```
funcall-interactively: Args out of range: [], 0
```
```
gscholar-bibtex--write-bibtex-to-file-impl: Args out of range: [], 0
```

**Comment by liar666** [comment]
Any news?

**Comment by GMTSE** [comment]
Apparently the error come and goes, just reloading the package / re-executing the command M-x gscholarxxx works...

**Comment by cute-jumper** [comment]
This is mostly a transient issue. Sometimes Google might refuse to give results for non-browser clients thus no results
