### ISSUE TITLE
no results from google scholar

### ISSUE THREAD

**Issue by adouzzy** [cute-jumper/gscholar-bibtex#6]
starting from today, google scholar doesn't return anything results.
They change their html format?

**Comment by cute-jumper** [comment]
Do you still have the problem?

**Comment by adouzzy** [comment]
It's a network specific problem. When I am at work, the Google scholar
webpage fetched asked me to enable JavaScript. When I got home, the problem
disappeared. I also try the scholar.py. It had the same problem. I think
gscholar is just fine. Sorry for opening an issue.

Cheers

**Comment by cute-jumper** [comment]
That's OK. Don't say sorry for opening issues:-) I'm just trying to figure out whether I need to make some changes to my code. Thanks.

**Comment by seakros** [comment]
I seem to be having this issue. I am on 0.300.x - can this be the cause of the issue?
IEEE Xplore source seems to work fine on the other hand..
