### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by cpitclaudel** [cute-jumper/gscholar-bibtex#8]
Hi,

I just started looking at this package. It's pretty nice. I did find the UI a bit confusing at first, though (in particular the operation of arrow keys).
Do you think there would be a way to reuse `reftex-select-label-mode` to select results? Most users of this package are probably already familiar with that interface.
Also, is there a way to just insert the selected result in the current file?

Thanks for your work on this package!

**Comment by cute-jumper** [comment]
Thanks for the suggestion.  I do think the UI can be improved! But `reftex-select-lable-mode` has a quite different user interface. All the labels, captions and section headings are shown, which I don't think it is easy to make it work in this package. Do you have something already in your mind about how this would work?

To insert the result in the current file, use `a` to select the current file and insert the result.

**Comment by cpitclaudel** [comment]
> Thanks for the suggestion. I do think the UI can be improved! But reftex-select-lable-mode has a quite different user interface. 

You're right, after having a look that interface is a nightmare to work with.

> To insert the result in the current file, use a to select the current file and insert the result.

Thanks. It's not the most convenient though; I was thinking of something that would insert the highlighted entry in the buffer that the search was started in.

**Comment by cute-jumper** [comment]
> I was thinking of something that would insert the highlighted entry in the buffer that the search was started in.

This use case doesn't seem to be common in my opinion(However, a quick key to copy the BibTeX entry might be useful though). You can define a custom function to achieve this:

    (defun gscholar-insert-bibtex-entry-in-caller-buffer ()
      (interactive)
      (gscholar-bibtex-retrieve-and-show-bibtex)
      (with-current-buffer gscholar-bibtex-caller-buffer
        (insert-buffer gscholar-bibtex-entry-buffer-name)))
    (define-key gscholar-bibtex-mode-map "i" #'gscholar-insert-bibtex-entry-in-caller-buffer)

**Comment by cpitclaudel** [comment]
Neat, thanks!
