### ISSUE TITLE
Chinese bibtex entry not showing correctly

### ISSUE THREAD

**Issue by et2010** [cute-jumper/gscholar-bibtex#9]
Querying works fine but the fields with Chinese characters are all empty.

![2016-05-06_093531_1680x943_scrot](https://cloud.githubusercontent.com/assets/11584902/15061983/186b33c6-136e-11e6-9109-6a93936416e2.png)

**Comment by cpitclaudel** [comment]
Thanks for the report; can you give me an example of a query that shows the problem?

**Comment by et2010** [comment]
![2016-05-06_100550_1680x943_scrot](https://cloud.githubusercontent.com/assets/11584902/15062401/57ac747e-1372-11e6-8c8a-2bf927c44fe3.png)

![2016-05-06_100600_1680x943_scrot](https://cloud.githubusercontent.com/assets/11584902/15062409/6490652e-1372-11e6-8204-9c33e7d67a31.png)

![2016-05-06_100618_1680x943_scrot](https://cloud.githubusercontent.com/assets/11584902/15062417/70cdf5ae-1372-11e6-9f27-46954aa4e906.png)

![2016-05-06_100651_1680x943_scrot](https://cloud.githubusercontent.com/assets/11584902/15062421/79936458-1372-11e6-87a5-0d37c75212ea.png)

**Comment by cpitclaudel** [comment]
Ok, I can reproduce this. (Just to clarify, this is not my project :)

**Comment by et2010** [comment]
I'm trying to figure it out but to no avail. I'm not skiiled at programming elisp, so any help will be appreciated.

**Comment by cute-jumper** [comment]
Thanks @et2010 @cpitclaudel . It's caused by the `User-Agent` and should be fix now. Please report any problems!
